version: "3.8"

services:
  gateway:
    container_name: spring-cloud-gateway
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
    - msa-network

networks:
  msa-network:
    external: true # 이미 만들어진 인프라 네트워크를 사용함