server:
  port: '8080'
jwt:
  secret: vQfU4V/l8+6RT35cOe/RqVbup1nA3YhoCywlEfCkFOA=
spring:
  cloud:
    gateway:
      routes:
      - id: user
        uri: http://localhost:8081
        predicates:
        - Path=/api/user/**
        filters:
        - StripPrefix=2
      - id: piece
        uri: http://localhost:8082
        predicates:
        - Path=/api/piece/**
        filters:
        - StripPrefix=2