server:
  port: '8080'
jwt:
  secret: ${jwt_secret}
spring:
  cloud:
    gateway:
      routes:
      - id: oauth
        uri: http://userservice:8081
        predicates:
        - Path=/oauth2/**,/login/oauth2/**
        filters:
        - PreserveHostHeader
      - id: user
        uri: http://userservice:8081
        predicates:
        - Path=/api/user/**
        filters:
        - StripPrefix=2
      - id: piece
        uri: http://pieceservice:8082
        predicates:
        - Path=/api/piece/**
        filters:
        - StripPrefix=2
logging:
  level:
    '[reactor.netty]': DEBUG
    '[org.springframework.web]': DEBUG